# Generated by Django 6.1.1 on 2026-09-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='group',
            field=models.CharField(choices=[('P', 'Primary'), ('S', 'Secondary')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('name', 'group'), name='unique_item_each_group'),
        ),
    ]
